CREATE TABLE account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance      DECIMAL(12,2),
    user_id      BIGINT                                  NOT NULL,
    account_type varchar(15) ,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE account
    ADD CONSTRAINT CK_BALANCE_NOT_NEGATIVE CHECK ( balance >= 0 );

ALTER TABLE account
    ADD CONSTRAINT CK_ACCOUNT_TYPE_VALID CHECK (account_type in ('MERCHANT','USER'));