CREATE TABLE transaction
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value           DECIMAL(12,2),
    from_account_id BIGINT                                  NOT NULL,
    to_account_id   BIGINT                                  NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_FROM_ACCOUNT FOREIGN KEY (from_account_id) REFERENCES account (id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_TO_ACCOUNT FOREIGN KEY (to_account_id) REFERENCES account (id);

ALTER TABLE transaction ADD CONSTRAINT CK_VALUE_NOT_NEGATIVE CHECK ( value >= 0 );